import Body from "@/components/Body";
import { api } from "@/utils/api";
import useScrollPosition from "hooks/useScrollPosition";
import { useDebouncedBookmarks } from "lib/zustand";
import Head from "next/head";
import React, { useEffect } from "react";
import Loader from "@/components/Loader";
import { TweetWithUser } from "interface";
import TweetList from "@/components/TweetList";
import Image from "next/legacy/image";

const BookmarkPage = () => {
  const scrollPosition = useScrollPosition();

  const { data, isLoading, isFetching, hasNextPage, fetchNextPage } =
    api.bookmark.getInfiniteUserBookmarks.useInfiniteQuery(
      {
        limit: 10,
      },
      {
        getNextPageParam: (lastPage) => lastPage.nextCursor,
      }
    );

  useEffect(() => {
    if (scrollPosition > 90 && hasNextPage && !isFetching) {
      fetchNextPage();
    }
  }, [scrollPosition, isFetching, hasNextPage, fetchNextPage]);

  const bookmarks =
    data?.pages.flatMap((page) =>
      page.bookmarks.map((bookmark) => bookmark.tweet)
    ) ?? [];

  const { bookmark: bookmarkValue } = useDebouncedBookmarks();

  const { data: searchBookmarks, isLoading: searchLoading } =
    api.bookmark.searchUserBookmarks.useQuery({
      term: bookmarkValue,
    });

  const debouncedBookmarks = searchBookmarks?.map((bookmark) => bookmark.tweet);

  return (
    <Body>
      <Head>
        <title>Bookmarks / UA You</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <BookmarkNav /> */}
      {isLoading ? (
        <Loader />
      ) : (
        <>
          {bookmarks?.length !== 0 ? (
            <>
              {bookmarkValue === "" ? (
                <TweetList tweets={bookmarks as unknown as TweetWithUser[]} />
              ) : (
                <>
                  {searchLoading ? (
                    <Loader />
                  ) : (
                    <TweetList tweets={debouncedBookmarks as TweetWithUser[]} />
                  )}
                </>
              )}
            </>
          ) : (
            <div className="items-centers flex flex-col justify-center gap-y-4 text-center ">
              <div className="relative mx-auto h-44 w-1/2">
                <Image
                  alt="no bookmarks"
                  layout="fill"
                  objectFit="cover"
                  src="/no-bookmarks.png"
                />
              </div>
              <h1 className="text-4xl font-bold text-neutral">
                Save tweets for later
              </h1>
              <p className="mx-auto w-1/2 text-start text-gray-500">
                Don’t let the good ones fly away! Bookmark Tweets to easily find
                them again in the future.
              </p>
            </div>
          )}
        </>
      )}
      {isFetching && hasNextPage ? (
        <div className="pb-16">
          <Loader />
        </div>
      ) : null}
    </Body>
  );
};

export default BookmarkPage;
