import React, { useEffect } from "react";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Body from "@/components/Body";
import Loader from "@/components/Loader";
import NavFeed from "@/components/NavFeed";
import { api } from "@/utils/api";
import useScrollPosition from "hooks/useScrollPosition";
import UsersList from "@/components/UsersList";

const Connect_people = () => {
  const { data: session } = useSession();
  const scrollPosition = useScrollPosition();

  const { data, isFetching, hasNextPage, fetchNextPage } =
    api.follow.getInfinitePeopleRecommendations.useInfiniteQuery(
      {
        limit: 10,
      },
      {
        getNextPageParam: (lastPage) => lastPage.nextCursor,
      }
    );

  useEffect(() => {
    if (scrollPosition > 90 && hasNextPage && !isFetching) {
      fetchNextPage();
    }
  }, [scrollPosition, isFetching, hasNextPage, fetchNextPage]);

  const users = data?.pages.flatMap((page) => page.users) ?? [];
  return (
    <Body>
      <Head>
        <title>Connect / UA You</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavFeed title="Connect" />
      <UsersList
        users={users?.filter((user) => user.id !== session?.user?.id)}
      />
      {isFetching && hasNextPage ? (
        <div className="pb-16">
          <Loader />
        </div>
      ) : null}
    </Body>
  );
};

export default Connect_people;
