import React, { useEffect } from "react";
import Head from "next/head";
import { useSession } from "next-auth/react";
import Body from "@/components/Body";
import CreateTweet from "@/components/CreateTweet";
import HomeNav from "@/components/HomeNav";
import TweetList from "@/components/TweetList";
import { api } from "@/utils/api";
import useScrollPosition from "hooks/useScrollPosition";
import Loader from "@/components/Loader";
import { TweetWithUser } from "interface";

const FollowingOnlyTweetsPage = () => {
  const scrollPosition = useScrollPosition();
  const { data, isLoading, isFetching, hasNextPage, fetchNextPage } =
    api.tweet.getFollowingInfiniteTweets.useInfiniteQuery(
      {
        limit: 10,
      },
      {
        getNextPageParam: (lastPage) => lastPage.nextCursor,
      }
    );

  useEffect(() => {
    if (scrollPosition > 90 && hasNextPage && !isFetching) {
      fetchNextPage();
    }
  }, [scrollPosition, isFetching, hasNextPage, fetchNextPage]);

  const tweets = data?.pages.flatMap((page) => page.followingTweets) ?? [];
  console.log(tweets);

  const { status } = useSession();

  return (
    <Body>
      <Head>
        <title>Following / UA You</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeNav />
      {status === "authenticated" ? <CreateTweet /> : null}
      {isLoading ? (
        <Loader />
      ) : (
        <>
          <TweetList tweets={tweets as TweetWithUser[]} />
        </>
      )}
      {isFetching && hasNextPage ? <Loader /> : null}
      {!hasNextPage && !isFetching ? (
        <p className="text-center text-gray-500">End of feed</p>
      ) : null}
    </Body>
  );
};

export default FollowingOnlyTweetsPage;
