import React from "react";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { v4 } from "uuid";
import Body from "@/components/Body";
import NavFeed from "@/components/NavFeed";
import { api } from "@/utils/api";
import NotificationComponent from "@/components/NotificationComponent";

const NotificationPage = () => {
  const { data: notifications } =
    api.notification.getUserNotifications.useQuery();

  const { data: session } = useSession();
  return (
    <Body>
      <Head>
        <title>{session?.user?.name} - UA You</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavFeed title="Notifications" />
      {notifications?.length !== 0 ? (
        <>
          {notifications?.map((notification) => (
            <NotificationComponent notification={notification} key={v4()} />
          ))}
        </>
      ) : (
        <h1 className="p-4 text-xl font-bold">No notifications here</h1>
      )}
    </Body>
  );
};

export default NotificationPage;
