import React from "react";
import Body from "@/components/Body";
import NavFeed from "@/components/NavFeed";
import TrendComponent from "@/components/TrendComponent";
import { v4 } from "uuid";
import { api } from "@/utils/api";
import Head from "next/head";

const TrendPage = () => {
  const { data } = api.hashtag.getTopHashtags.useQuery();

  return (
    <Body>
      <Head>
        <title>Trends / UA You</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavFeed title="Trends" />
      {data?.map((hashtag) => (
        <TrendComponent hashtag={hashtag} key={v4()} />
      ))}
    </Body>
  );
};

export default TrendPage;
